// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Main character0":return img`
.....f..........
..fff1fffff.....
..f11111111f....
.f1111111111f...
f1111111bb11f...
.ffbbbbbbb11f...
..fdfdddfb1df...
..fdfdddfbbbf...
..fddddddbbf....
...feeeeeef.....
...fffffffef....
...feeefeeef....
..ffeeffeeedf...
.fdfeeeeeefdf...
.fffbbbcccfff...
...fbbbbccf.....
...fbf.fccf.....
....ff..fff.....
...fff..ff......
................
`;
            case "7[-=fLG=Q7OK+WS{0Q2I":
            case "Main character":return img`
................
................
.....ffffffff...
....f11111111f..
...11111111111f.
...1111bb1111ff.
...fd1bfbbbfbf..
...fbbbfdddfdf..
....fbbddddddf..
.....feeeeeef...
....fefffffff...
....fbeefeeef...
...fdbbeffeeff..
...fdfbeeeeefdf.
...fffcccbbbfff.
.....fccbffb....
......ff..fb....
......ff..ff....
................
................
`;
            case "image2":
            case "Main character1":return img`
................
................
...ffffffff.....
..f11111111f....
.f11111111111...
.ff1111bb1111...
..fbfbbbfb1df...
..fdfdddfbbbf...
..fddddddbbf....
...feeeeeef.....
...fffffffef....
...feeefeebf....
..ffeeffebbdf...
.fdfeeeeebfdf...
.fffbbbcccfff...
....bffbccf.....
....bf..ff......
....ff..ff......
................
................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim0":
            case "anim2":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
